---
# handlers file for ansible-jmx-exporter
- name: reload prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: POST
  listen: "reload prometheus"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups.prometheus | default([]) }}"
